from __future__ import annotations
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, field_validator, ValidationError
from common.llm_client import get_llm_client
from orchestra.situation import SituationContext
from orchestra.registry import CapabilityRegistry, RegistryCapability


# ============================================================================
# Planner Constants
# ============================================================================

MAX_PLAN_STEPS = 10
MAX_DEPENDENCY_DEPTH = 5
MAX_CANDIDATES_PER_NEED = 5


# ============================================================================
# Custom Exceptions
# ============================================================================

class PlanningError(Exception):
    """Base class for all planning errors."""
    pass


class PlanValidationError(PlanningError):
    """Raised when a proposed plan fails validation checks."""
    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.details = details or {}


# ============================================================================
# Pydantic Planner Schema Contracts
# ============================================================================

class InformationNeed(BaseModel):
    """
    Structured representation of a dynamic query or validation requirement
    derived from the SituationContext.
    """
    need_id: str
    description: str
    priority: str
    source_context: str
    related_facts: list[str] = Field(default_factory=list)
    related_uncertainties: list[str] = Field(default_factory=list)
    related_information_gaps: list[str] = Field(default_factory=list)

    @field_validator("priority")
    @classmethod
    def validate_priority(cls, v: str) -> str:
        allowed = ["high", "medium", "low"]
        if v not in allowed:
            raise ValueError(f"Invalid priority '{v}'. Must be one of {allowed}")
        return v


class InformationNeedsList(BaseModel):
    """Container schema for LLM structured output parsing of needs."""
    needs: List[InformationNeed]


class CapabilityCandidate(BaseModel):
    """
    Evaluated option representing a match between a registry capability
    and an information need.
    """
    capability_id: str
    specialist: str
    description: str
    information_need_id: str
    relevance_score: float = Field(ge=0.0, le=1.0)
    explanation: str


class ScoredCandidateRaw(BaseModel):
    """Raw candidate schema returned from semantic LLM matching."""
    capability_id: str
    information_need_id: str
    relevance_score: float = Field(ge=0.0, le=1.0)
    explanation: str


class ScoredCandidateRawList(BaseModel):
    """Container schema for LLM structured output parsing of scored candidates."""
    candidates: List[ScoredCandidateRaw]


class PlannerResult(BaseModel):
    """Container preserving all evaluated and filtered capability candidates."""
    all_ranked_candidates: List[CapabilityCandidate] = Field(default_factory=list)
    selected_candidates: List[CapabilityCandidate] = Field(default_factory=list)


# ============================================================================
# Phase 3B Planning Schema Contracts
# ============================================================================

class ProposedPlanStep(BaseModel):
    """A proposed step of the plan generated by the LLM."""
    step_id: str
    information_need_id: str
    capability_id: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    dependency_reasoning: dict[str, str] = Field(default_factory=dict)
    expected_output: str
    reasoning: str


class ProposedPlan(BaseModel):
    """Plan container proposed by the LLM."""
    steps: list[ProposedPlanStep] = Field(default_factory=list)
    omitted_need_reasons: dict[str, str] = Field(default_factory=dict)


class ValidatedPlanStep(BaseModel):
    """Authoritative, registry-grounded and validated plan step."""
    step_id: str
    information_need_id: str
    capability_id: str
    specialist: str
    endpoint: str
    description: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    dependency_reasoning: dict[str, str] = Field(default_factory=dict)
    expected_output: str
    reasoning: str


class ValidatedPlan(BaseModel):
    """Final grounded execution plan ready for execution loops."""
    steps: list[ValidatedPlanStep] = Field(default_factory=list)


# ============================================================================
# Step 1 — Information Need Extraction
# ============================================================================

def extract_information_needs(situation: SituationContext) -> list[InformationNeed]:
    """
    Translates a complex SituationContext objective, facts, gaps, and uncertainties
    into a structured list of InformationNeed requirements using UnifiedLLMClient.
    """
    client = get_llm_client()

    prompt = f"""
Analyze the following procurement situation context and identify the core information needs that must be resolved.
Information needs must specify WHAT needs to be resolved or verified.

CRITICAL RULE: Do NOT mention any specific specialist systems (such as Sentinel, Trustline, Precedent, Arbiter) or specific routing instructions.

Situation Objective: {situation.objective}
Known Facts: {situation.known_facts}
Uncertainties: {situation.uncertainties}
Information Gaps: {situation.information_gaps}

Generate a structured list of InformationNeed items. Each item must have a unique need_id (e.g. 'need_1', 'need_2'), priority (high/medium/low), and related context from the situation.
"""
    raw_res = client.generate_structured(prompt=prompt, schema=InformationNeedsList)
    needs_list = InformationNeedsList.model_validate(raw_res)

    # Enforce unique need_ids and reject duplicate entries
    seen_ids = set()
    validated_needs = []
    for need in needs_list.needs:
        if need.need_id in seen_ids:
            continue
        seen_ids.add(need.need_id)
        validated_needs.append(need)
    return validated_needs


# ============================================================================
# Step 2 — Dynamic Capability Evaluation
# ============================================================================

def evaluate_capabilities(
    needs: list[InformationNeed],
    registry: CapabilityRegistry
) -> list[CapabilityCandidate]:
    """
    Dynamically loads capabilities from the registry and evaluates their relevance
    against the list of extracted InformationNeed requirements.
    """
    if not needs:
        return []

    client = get_llm_client()
    all_caps = registry.list_capabilities()

    # Format the lists for LLM evaluation
    needs_desc = "\n".join([
        f"- ID: {n.need_id} | Description: {n.description} | Priority: {n.priority} | Context: {n.source_context}"
        for n in needs
    ])

    caps_desc = "\n".join([
        f"- ID: {c.id} | Description: {c.description} | Use When: {c.use_when}"
        for c in all_caps
    ])

    prompt = f"""
You are an expert AI orchestrator evaluating how well registered specialist capabilities can resolve a list of current project Information Needs.

Current Project Information Needs:
{needs_desc}

Registered Specialist Capabilities:
{caps_desc}

For each Information Need, evaluate the relevance of EACH registered capability.
Determine if a capability is semantically relevant to solving the information need.
Generate a list of candidate matches. For each match, provide:
- capability_id: MUST exactly match one of the registered capability IDs.
- information_need_id: MUST exactly match one of the Information Need IDs.
- relevance_score: From 0.0 (no relevance) to 1.0 (highly relevant).
- explanation: Brief rationale for why this capability fits this need.

CRITICAL: Do NOT invent or fabricate capability IDs. Every capability_id must exist in the registered list above.
"""
    raw_res = client.generate_structured(prompt=prompt, schema=ScoredCandidateRawList)
    raw_list = ScoredCandidateRawList.model_validate(raw_res)

    # Map of valid needs for validation
    needs_map = {n.need_id: n for n in needs}
    processed_candidates: List[CapabilityCandidate] = []

    for candidate in raw_list.candidates:
        # 1. Reject any candidate whose capability_id does not exist in the registry
        if candidate.capability_id not in registry.capabilities:
            print(f"[Planner] Discarding fabricated capability: {candidate.capability_id}")
            continue

        # 2. Reject any candidate whose information_need_id does not exist in the extracted needs
        if candidate.information_need_id not in needs_map:
            print(f"[Planner] Discarding invalid need reference: {candidate.information_need_id}")
            continue

        # 3. Resolve specialist and capability description from CapabilityRegistry
        registry_cap = registry.get(candidate.capability_id)
        specialist = registry_cap.specialist
        description = registry_cap.description

        # 4. Validate relevance_score range
        score = max(0.0, min(1.0, candidate.relevance_score))

        processed_candidates.append(CapabilityCandidate(
            capability_id=candidate.capability_id,
            specialist=specialist,
            description=description,
            information_need_id=candidate.information_need_id,
            relevance_score=score,
            explanation=candidate.explanation
        ))

    # 5. Deduplicate candidates using (information_need_id, capability_id)
    # Retain the candidate with the highest relevance score
    deduped: Dict[tuple[str, str], CapabilityCandidate] = {}
    for c in processed_candidates:
        key = (c.information_need_id, c.capability_id)
        if key in deduped:
            if c.relevance_score > deduped[key].relevance_score:
                deduped[key] = c
        else:
            deduped[key] = c

    return list(deduped.values())


# ============================================================================
# Step 3 — Deterministic Ranking & Filtering
# ============================================================================

def rank_candidates(
    candidates: list[CapabilityCandidate],
    needs: list[InformationNeed],
    relevance_threshold: float = 0.5
) -> PlannerResult:
    """
    Ranks the list of candidates based on:
    1. relevance_score descending
    2. priority descending (high > medium > low)
    3. capability_id lexicographically ascending
    4. information_need_id lexicographically ascending
    Filters and outputs both complete and threshold-filtered lists.
    """
    priority_map = {"high": 3, "medium": 2, "low": 1}
    need_priorities = {n.need_id: priority_map.get(n.priority, 0) for n in needs}

    def sort_key(c: CapabilityCandidate):
        return (
            -c.relevance_score,
            -need_priorities.get(c.information_need_id, 0),
            c.capability_id,
            c.information_need_id
        )

    all_ranked = sorted(candidates, key=sort_key)
    selected = [c for c in all_ranked if c.relevance_score >= relevance_threshold]

    return PlannerResult(
        all_ranked_candidates=all_ranked,
        selected_candidates=selected
    )


# ============================================================================
# Phase 3B — Plan Generation and Dependency Validation
# ============================================================================

class ContractCompatibilityResponse(BaseModel):
    """Pydantic model parsed from LLM semantic compatibility validator."""
    is_compatible: bool
    reason: str


def validate_capability_contract(
    objective: str,
    expected_output: str,
    registry_cap: RegistryCapability
) -> bool:
    """
    Generic registry-driven semantic contract verification using LLM.
    Rejects steps that assign unrelated tasks to capabilities based on
    manifest metadata constraints (use_when, description, produces).
    """
    client = get_llm_client()

    prompt = f"""
Verify whether the proposed plan step objective and expected output are compatible with the registered capability manifest contract.

Registered Capability Manifest:
- ID: {registry_cap.id}
- Description: {registry_cap.description}
- Use When Rules: {registry_cap.use_when}
- Produces Output Fields: {registry_cap.produces}

Proposed Plan Step:
- Objective: {objective}
- Expected Output: {expected_output}

Decide whether this proposed plan step is compatible with the declared manifest capability.
You must reject the step (is_compatible = false) if the objective or expected output is completely unrelated to what the capability is designed to do.

Output JSON format matching this schema:
{{
  "is_compatible": true/false,
  "reason": "Brief explanation of compatibility or mismatch"
}}
"""
    raw_res = client.generate_structured(prompt=prompt, schema=ContractCompatibilityResponse)
    res = ContractCompatibilityResponse.model_validate(raw_res)
    return res.is_compatible


def generate_plan(
    situation: SituationContext,
    needs: list[InformationNeed],
    candidates: list[CapabilityCandidate],
    registry: CapabilityRegistry
) -> ProposedPlan:
    """
    Generates a proposed planning sequence by filtering candidates to top 5 per need
    and calling UnifiedLLMClient structured proposal.
    """
    client = get_llm_client()

    # 1. Filter candidates to top 5 per need
    by_need: Dict[str, List[CapabilityCandidate]] = {}
    for c in candidates:
        by_need.setdefault(c.information_need_id, []).append(c)

    eligible_candidates: List[CapabilityCandidate] = []
    for need_id, c_list in by_need.items():
        sorted_c = sorted(c_list, key=lambda x: -x.relevance_score)
        eligible_candidates.extend(sorted_c[:MAX_CANDIDATES_PER_NEED])

    if not eligible_candidates:
        return ProposedPlan()

    needs_desc = "\n".join([
        f"- ID: {n.need_id} | Priority: {n.priority} | Description: {n.description}"
        for n in needs
    ])

    candidates_desc = "\n".join([
        f"- Need: {c.information_need_id} | Capability ID: {c.capability_id} (Score: {c.relevance_score}) | Description: {c.description}"
        for c in eligible_candidates
    ])

    prompt = f"""
You are an expert procurement and scheduling project planner. Your objective is to formulate a structured ProposedPlan to address the current Information Needs of the project.

Situation Objective: {situation.objective}
Known Facts: {situation.known_facts}
Uncertainties: {situation.uncertainties}
Information Gaps: {situation.information_gaps}

Current Information Needs:
{needs_desc}

Eligible Candidate Capabilities (Phase 3A Evaluated):
{candidates_desc}

Formulate a plan consisting of sequential or parallel steps.
RULES:
1. Candidate Constraints: You may select only from the provided eligible candidates. Do not invent capabilities, information needs, specialists, endpoints, or dependencies.
2. Parallel Preference: Prefer independent steps unless one step genuinely requires information produced by another step.
3. Dependency Justification: Every dependency must identify why the output of the dependency is required before the dependent step can execute. Add this justification to `dependency_reasoning` mapping the dependency step_id to a clear explanation.
4. Omission Rules: High-priority information needs must be addressed. If a medium or low priority need is intentionally omitted, provide a reason in `omitted_need_reasons`.
"""
    raw_res = client.generate_structured(prompt=prompt, schema=ProposedPlan)
    proposed = ProposedPlan.model_validate(raw_res)
    return proposed


def validate_and_normalize_plan(
    proposed: ProposedPlan,
    needs: list[InformationNeed],
    candidates: list[CapabilityCandidate],
    registry: CapabilityRegistry
) -> ValidatedPlan:
    """
    Deterministically validates plan structure, priorities, DAG dependencies,
    reasoning entries, step limits, and capability manifest contracts.
    Returns a topologically sorted and tie-broken ValidatedPlan.
    """
    # 1. Enforce step count limit
    if len(proposed.steps) > MAX_PLAN_STEPS:
        raise PlanValidationError(
            f"Plan exceeds maximum limit of {MAX_PLAN_STEPS} steps (proposed: {len(proposed.steps)})."
        )

    needs_map = {n.need_id: n for n in needs}

    # Group eligible candidates top 5
    by_need: Dict[str, List[CapabilityCandidate]] = {}
    for c in candidates:
        by_need.setdefault(c.information_need_id, []).append(c)

    eligible_caps = set()
    candidate_scores = {}
    for need_id, c_list in by_need.items():
        sorted_c = sorted(c_list, key=lambda x: -x.relevance_score)
        for c in sorted_c[:MAX_CANDIDATES_PER_NEED]:
            eligible_caps.add((c.information_need_id, c.capability_id))
            candidate_scores[(c.information_need_id, c.capability_id)] = c.relevance_score

    # Check high/medium/low priority coverage (Rule 7)
    addressed_need_ids = {step.information_need_id for step in proposed.steps}
    for need in needs:
        if need.priority == "high":
            if need.need_id not in addressed_need_ids:
                raise PlanValidationError(
                    f"High-priority information need '{need.need_id}' is not addressed in the proposed plan."
                )
        elif need.priority in ["medium", "low"]:
            if need.need_id not in addressed_need_ids:
                reason = proposed.omitted_need_reasons.get(need.need_id)
                if not reason or not reason.strip():
                    raise PlanValidationError(
                        f"Need '{need.need_id}' (priority: {need.priority}) is omitted but lacks a valid justification in omitted_need_reasons."
                    )

    # Validate each step independently
    step_map: Dict[str, ProposedPlanStep] = {}
    for step in proposed.steps:
        if step.step_id in step_map:
            raise PlanValidationError(f"Duplicate step ID '{step.step_id}' found in proposed plan.")
        step_map[step.step_id] = step

        if step.information_need_id not in needs_map:
            raise PlanValidationError(
                f"Step '{step.step_id}' references unknown information need ID '{step.information_need_id}'."
            )

        if step.capability_id not in registry.capabilities:
            raise PlanValidationError(
                f"Step '{step.step_id}' references unknown capability ID '{step.capability_id}'."
            )

        if (step.information_need_id, step.capability_id) not in eligible_caps:
            raise PlanValidationError(
                f"Step '{step.step_id}' uses capability '{step.capability_id}' for need '{step.information_need_id}' which is not in the eligible candidates list."
            )

        # Enforce contract validation (Rule 9)
        reg_cap = registry.get(step.capability_id)
        if not validate_capability_contract(step.objective, step.expected_output, reg_cap):
            raise PlanValidationError(
                f"Proposed step '{step.step_id}' objective or expected output is incompatible with the declared manifest capability contract of '{step.capability_id}'."
            )

    # Validate dependency fields, self-dependencies, and reasoning (Rule 8)
    for step_id, step in step_map.items():
        normalized_deps = []
        seen_deps = set()
        for dep in step.depends_on:
            if dep == step_id:
                raise PlanValidationError(f"Step '{step_id}' cannot depend on itself.")
            if dep not in step_map:
                raise PlanValidationError(
                    f"Step '{step_id}' depends on step '{dep}' which is not defined in the plan."
                )

            # Every dependency must have matching reasoning
            reason = step.dependency_reasoning.get(dep)
            if not reason or not reason.strip():
                raise PlanValidationError(
                    f"Step '{step_id}' is missing a valid dependency reasoning explanation for '{dep}'."
                )

            if dep not in seen_deps:
                seen_deps.add(dep)
                normalized_deps.append(dep)

        step.depends_on = normalized_deps

    # Enforce maximum dependency depth
    depths: Dict[str, int] = {}
    def get_depth(sid: str) -> int:
        if sid in depths:
            return depths[sid]
        s = step_map[sid]
        if not s.depends_on:
            depths[sid] = 1
            return 1
        depths[sid] = 999
        max_d = max(get_depth(d) for d in s.depends_on)
        depths[sid] = max_d + 1
        return depths[sid]

    for sid in step_map:
        d = get_depth(sid)
        if d > 900:
            raise PlanValidationError("Cycle detected during dependency depth calculation.")
        if d > MAX_DEPENDENCY_DEPTH:
            raise PlanValidationError(
                f"Plan dependency depth exceeds limit of {MAX_DEPENDENCY_DEPTH} (calculated depth: {d} for step '{sid}')."
            )

    # Topological sorting (Kahn's algorithm) with deterministic tie-breaking
    indegrees = {sid: 0 for sid in step_map}
    adjacency = {sid: [] for sid in step_map}

    for sid, step in step_map.items():
        for dep in step.depends_on:
            adjacency[dep].append(sid)
            indegrees[sid] += 1

    zero_in = [sid for sid, ind in indegrees.items() if ind == 0]
    
    priority_map = {"high": 3, "medium": 2, "low": 1}
    need_priorities = {n.need_id: priority_map.get(n.priority, 0) for n in needs}

    def sort_independent_steps(step_ids: List[str]) -> List[str]:
        def key_func(sid: str):
            step = step_map[sid]
            score = candidate_scores.get((step.information_need_id, step.capability_id), 0.0)
            priority = need_priorities.get(step.information_need_id, 0)
            return (
                -priority,               # 1. priority descending
                -score,                  # 2. relevance_score descending
                step.capability_id,      # 3. capability_id lexicographically ascending
                step.step_id             # 4. step_id lexicographically ascending
            )
        return sorted(step_ids, key=key_func)

    ordered_step_ids = []
    while zero_in:
        zero_in = sort_independent_steps(zero_in)
        curr = zero_in.pop(0)
        ordered_step_ids.append(curr)
        for neighbor in adjacency[curr]:
            indegrees[neighbor] -= 1
            if indegrees[neighbor] == 0:
                zero_in.append(neighbor)

    if len(ordered_step_ids) != len(step_map):
        raise PlanValidationError("Cycle detected in plan dependency graph.")

    # Ground validated steps with authoritative registry metadata
    validated_steps = []
    for sid in ordered_step_ids:
        proposed_step = step_map[sid]
        reg_cap = registry.get(proposed_step.capability_id)
        
        dep_reasoning = {dep: proposed_step.dependency_reasoning[dep] for dep in proposed_step.depends_on}
        
        validated_steps.append(ValidatedPlanStep(
            step_id=sid,
            information_need_id=proposed_step.information_need_id,
            capability_id=proposed_step.capability_id,
            specialist=reg_cap.specialist,
            endpoint=reg_cap.canonical_endpoint,
            description=reg_cap.description,
            objective=proposed_step.objective,
            depends_on=proposed_step.depends_on,
            dependency_reasoning=dep_reasoning,
            expected_output=proposed_step.expected_output,
            reasoning=proposed_step.reasoning
        ))

    return ValidatedPlan(steps=validated_steps)
