# -*- coding: utf-8 -*-
"""
Compass – Gemini‑enabled decision synthesis service.

Provides:
* GET  /health          – health check with Gemini availability flag
* GET  /capabilities    – list of supported capabilities (compass.recommend)
* POST /compass/recommend – synthesize procurement recommendation using Google Gemini.

The endpoint expects an AgentTask payload (see schemas.py) and returns an AgentResult
containing a Recommendation generated by Gemini.
"""

from os import getenv
import time
import json

import google.genai as genai
from google.genai import types
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware

# Load environment variables from .env
from dotenv import load_dotenv
load_dotenv()

from schemas import (
    AgentResult,
    AgentTask,
    Recommendation,
    new_id,
    utcnow,
)

app = FastAPI(
    title="Compass",
    description="Decision synthesis specialist powered by Google Gemini.",
    version="0.1.0",
)

# Configure CORS to allow the UI origin (same host) while not disabling security globally
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8000", "http://127.0.0.1:8000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve static files (including the test UI) under /static
app.mount("/static", StaticFiles(directory="static"), name="static")

AGENT_NAME = "compass"

# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------

def _configure_gemini() -> genai.Client:
    """Configure the Gemini client and return a Client instance.

    Raises:
        RuntimeError: If the API key is missing.
    """
    api_key = getenv("GEMINI_API_KEY") or getenv("GOOGLE_API_KEY")
    if api_key:
        api_key = api_key.strip()
    if not api_key:
        raise RuntimeError(
            "API key not set in environment. Define GEMINI_API_KEY (or GOOGLE_API_KEY) with a valid Gemini API key."
        )
    # Initialize the new genai client
    client = genai.Client(api_key=api_key)
    print(f"🔧 Gemini client initialized with model alias gemini-flash-latest")
    return client


def _build_prompt(task: AgentTask) -> str:
    """Construct a detailed prompt for Gemini based on the supplied ``task``.

    The prompt explicitly asks Gemini to return **only** a JSON object that matches
    the ``Recommendation`` schema defined in ``schemas.py``.
    """
    context_str = json.dumps(task.context or {}, indent=2)
    prompt = (
        "You are a senior procurement decision analyst. Synthesize the following "
        "context into a single, defensible recommendation. Answer the required "
        "questions and return ONLY a JSON object that matches the Recommendation "
        "schema defined in the service (no extra text, no markdown).\n"
        "Do NOT fabricate any data that is not present in the context.\n"
        f"Task ID: {task.task_id}\n"
        f"Project ID: {task.project_id}\n"
        f"Situation ID: {task.context.get('situation_id', 'unknown') if task.context else 'unknown'}\n"
        "Context:\n"
        f"{context_str}"
    )
    return prompt


def _call_gemini(task: AgentTask) -> Recommendation:
    """Invoke Gemini and parse its JSON response into a ``Recommendation`` model.

    Raises:
        RuntimeError: If Gemini returns malformed JSON or the parsing fails.
    """
    client = _configure_gemini()
    prompt = _build_prompt(task)
    # Retry logic – handle temporary UNAVAILABLE (503) errors and fallback models
    max_retries = 3
    backoff = 2  # seconds
    models_to_try = ["gemini-flash-latest", "gemini-1.5-pro"]
    response = None
    for model_name in models_to_try:
        for attempt in range(1, max_retries + 1):
            try:
                response = client.models.generate_content(
                    model=model_name,
                    contents=prompt,
                    config=types.GenerateContentConfig(response_mime_type="application/json"),
                )
                break  # success
            except Exception as exc:
                if "UNAVAILABLE" in str(exc) and attempt < max_retries:
                    wait_time = backoff * attempt
                    print(f"⚡ Gemini API unavailable for {model_name} (attempt {attempt}/{max_retries}); retrying in {wait_time}s...")
                    time.sleep(wait_time)
                    continue
                else:
                    print(f"❌ Gemini call failed for {model_name}: {exc}")
                    break
        if response:
            break
    if not response:
        if not response:
        # All attempts failed – return a static placeholder recommendation
        print("⚠️ All Gemini attempts failed; returning placeholder recommendation.")
        dummy = {
            "recommendation_id": new_id("rec"),
            "situation_id": "unknown",
            "recommendation": "No recommendation could be generated due to service unavailability.",
            "rationale": "Fallback response",
            "contributing_factors": [],
            "cost_impact": None,
            "schedule_impact": None,
            "risk_exposure": "unknown",
            "confidence": 0.0,
            "alternatives_considered": [],
        }
        return Recommendation.parse_obj(dummy)
    text = response.text.strip()
    # Strip possible markdown fences
    if text.startswith("```"):
        text = "\n".join(text.splitlines()[1:-1])
    try:
        data = json.loads(text)
    except Exception as exc:
        raise RuntimeError(f"Failed to decode Gemini JSON: {exc}")
    # Let Pydantic validate the structure
    return Recommendation.parse_obj(data)

# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@app.get("/health")
def health() -> dict:
    """Return a simple health status and indicate whether Gemini is configured."""
    return {
        "status": "ok",
        "agent": AGENT_NAME,
        "time": utcnow().isoformat(),
        "gemini_available": bool(getenv("GEMINI_API_KEY")),
        "claude_available": bool(getenv("GEMINI_API_KEY")),  # backward‑compatibility flag
    }


@app.get("/capabilities")
def capabilities() -> dict:
    """List the capabilities exposed by this service."""
    return {"capabilities": ["compass.recommend"]}


@app.post("/compass/recommend", response_model=AgentResult)
def recommend(task: AgentTask) -> AgentResult:
    """Generate a procurement recommendation using Gemini.

    The endpoint validates the capability, ensures the Gemini API key is present,
    forwards the context to Gemini, and wraps the resulting ``Recommendation`` in an
    ``AgentResult`` structure expected by the ORCHESTRA orchestrator.
    """
    if task.capability != "compass.recommend":
        raise HTTPException(
            status_code=400,
            detail=f"Compass does not support capability '{task.capability}'",
        )
    if not getenv("GEMINI_API_KEY"):
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY not configured")

    try:
        recommendation = _call_gemini(task)
    except Exception as exc:
        raise HTTPException(status_code=502, detail=str(exc))

    return AgentResult(
        agent=AGENT_NAME,
        task_id=task.task_id,
        status="completed",
        findings=[
            {
                "type": "recommendation",
                "explanation": "Gemini synthesized a recommendation based on provided context.",
                "data": recommendation.model_dump(),
            }
        ],
        claims=[],
        evidence=[],
        confidence=recommendation.confidence,
        risks=[],
        recommended_next_capabilities=[],
        receipt_id=new_id("receipt"),
    )

@app.get("/", response_class=HTMLResponse)
def root():
    """Serve the Compass Test Console UI as the landing page."""
    with open("static/compass_test.html", "r", encoding="utf-8") as f:
        return HTMLResponse(content=f.read())
